name: CI/CD Angular SSR Docker

on:
  push:
    branches:
      - main       # ou develop si tu veux la branche develop comme principale
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Angular SSR
      - name: Build Angular SSR
        run: npm run build

      # 5. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t badrcherhoune/application-ci:latest .

      # 7. Push Docker image
      - name: Push Docker image
        run: docker push badrcherhoune/application-ci:latest

      # 8. (Optionnel) Déployer sur serveur distant via SSH
      #- name: Deploy to server
      #  uses: appleboy/ssh-action@v0.1.8
      #  with:
      #    host: ${{ secrets.SERVER_HOST }}
      #    username: ${{ secrets.SERVER_USER }}
      #    key: ${{ secrets.SERVER_SSH_KEY }}
      #    script: |
      #      docker pull badrcherhoune/application-ci:latest
      #      docker stop application-ci || true
      #      docker rm application-ci || true
      #      docker run -d -p 4200:4000 --name application-ci badrcherhoune/application-ci:latest
